version: 0.0
os: linux

files:
  - source: /
    destination: /usr/share/nginx/html
    overwrite: true

permissions:
  - object: /usr/share/nginx/html
    owner: nginx
    group: nginx
    mode: 755
    type:
      - file
      - directory

hooks:
  ApplicationStop:
    - location: scripts/stop_nginx.sh
      timeout: 30
      runas: root

  BeforeInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 30
      runas: root

  ValidateService:
    - location: scripts/validate_nginx.sh
      timeout: 30
      runas: root
