version: 0.2

phases:
  install:
    commands:
      - echo "Installing nginx"
      - yum update -y
      - yum install -y nginx
  build:
    commands:
      - echo "Starting nginx"
      - systemctl start nginx || nginx
      - echo "Testing nginx locally"
      - curl http://localhost
      - cp index.html /usr/share/nginx/html/index.html
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - "**/*"
